### PR TITLE
Fix deprecation warnings in preamble of FileSystem-Git package

### PR DESCRIPTION
**Pull request by LinqLover**
As mentioned [here](https://github.com/hpi-swa/Squot/pull/257#issuecomment-575900953).

### CODE REVIEW

**Comment by j4yk** [comment]
Wait a minute, I might have renamed the instance variable from isInFilemode to isInFileMode back then. In that case this is the migration code and it must stay.

Do you mean Squot deletes the postscript on save? That would be a bug of course.

**Comment by j4yk** [comment]
Here it is: https://github.com/LinqLover/Squot/commit/cf6fe5f5dc8cd602b559ecc7e978f2b89dfc3026

Looks like the change is okay then. Can you check again please? I just got up and should not review code in this state.  :-)

**Comment by LinqLover** [comment]
I don't see the problem, but I never actually faced with the implementation of Squot :) The postscript should be executed after loading the latest version, so `#isInFileMode` has been installed and can be safely used, can't it? The postscript does not touch the instance variables!

**Comment by LinqLover** [comment]
> Do you mean Squot deletes the postscript on save? That would be a bug of course.

Need to reproduce this.

**Comment by LinqLover** [comment]
Hey @j4yk, any updates on this PR? :-)

**Comment by j4yk** [comment]
Alright what was this...

There were originally two instance variables isInFilemode and isSubmodule; the accessors were named alike; the variables were replaced by one called 'mode'; there is a new test method isInFileMode; in the meanwhile isInFilemode has been removed.

So the current script is broken, but not triggered because nobody loads Squot via Monticello or has GitTreeEntry instances already. (?)

Assuming this is a fresh installation, all is fine because there are no GitTreeEntry instances yet.

Assuming this is an old installation with the old inst vars, there will only be the old accessors. So these must be used.

Assuming this is a more recent installation with the new inst var, nothing should actually be done here because the migration has already happened.

So just changing the selector to the new one does not fulfill the purpose after all. What is needed is a guard to not run this conversion if it is not necessary. Both in the preamble and in the postscript. I guess this is what I meant in my earlier comment "the script could use an upgrade to be idempotent."

**Pull request closed without merging**
