### PR TITLE
Add license

### LINKED ISSUE #154: LICENSE missing

### PR DESCRIPTION
**Pull request by j4yk**
fixes #154

@fniephaus, @marceltaeumel, @tom95, @corinnaj do you agree to put your contributions to Squot under the MIT license?

### CODE REVIEW

**Comment by fniephaus** [comment]
Agreed.

**Comment by tom95** [comment]
Yes, agree

**Comment by corinnaj** [comment]
Agreed.

**Comment by marceltaeumel** [comment]
Agreed.

**Pull request merged**
